apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-balti-salahdevopsportfolio-com-tls
  namespace: monitoring # Replace with the namespace where your application is deployed
spec:
  secretName: grafana-balti-tls-secret # The secret where the TLS certificate will be stored
  issuerRef:
    name: letsencrypt-prod # Reference to the ClusterIssuer
    kind: ClusterIssuer
  commonName: grafana.balti.salahdevopsportfolio.com
  dnsNames:
    - grafana.balti.salahdevopsportfolio.com
  acme:
    config:
      - http01:
          ingressClass: nginx # The ingress class used by the NGINX Ingress Controller
        domain: grafana.balti.salahdevopsportfolio.com # The domain for which the certificate is requested 