grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  ingress:
    enabled: true
    pathType: Prefix
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.balti.salahdevopsportfolio.com
    path : /
    tls:
      - secretName: grafana-salah-tls-secret # The secret where the TLS certificate will be stored
        hosts:
          - grafana.balti.salahdevopsportfolio.com 

prometheus:
  enabled: true
  ingress:
    enabled: true
    pathType: Prefix
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - prometheus.balti.salahdevopsportfolio.com
    path : /
    tls:
      - secretName: prometheus-balti-tls-secret # The secret where the TLS certificate will be stored
        hosts:
          - prometheus.balti.salahdevopsportfolio.com

  